USE Prohgmena;

-- table 1.14
CREATE TABLE Road_Type_Lookup (
  id TINYINT PRIMARY KEY NOT NULL,  
  val varchar(30) NOT NULL,  
);

INSERT INTO Road_Type_Lookup VALUES 
(1, 'Roundabout'),
(2, 'One way street'),
(3, 'Dual carriageway'),
(6, 'Single carriageway'),
(7, 'Slip road'),
(9, 'Unknown');

-- table 1.22
CREATE TABLE Weather_Lookup (
  id TINYINT PRIMARY KEY NOT NULL,  
  val varchar(50) NOT NULL,  
);

INSERT INTO Weather_Lookup VALUES
(1, 'Fine without high winds'),
(2, 'Raining without high winds'),
(3, 'Snowing without high winds'),
(4, 'Fine with high winds'),
(5, 'Raining with high winds'),
(6, 'Snowing with high winds'),
(7, 'Fog or mist — if hazard'),
(8, 'Other'),
(9, 'Unknown');

-- table 1.23
CREATE TABLE Road_Surface_Lookup (
  id TINYINT PRIMARY KEY NOT NULL,  
  val varchar(50) NOT NULL,  
);

INSERT INTO Road_Surface_Lookup VALUES 
(1, 'Dry'),
(2, 'Wet / Damp'),
(3, 'Snow'),
(4, 'Frost / Ice'),
(5, 'Flood(surface water over 3cm deep)');


-- table police_force
CREATE TABLE Police_Force_Lookup (
  id TINYINT PRIMARY KEY NOT NULL,  
  val varchar(50) NOT NULL,  
);


INSERT INTO Police_Force_Lookup VALUES
(1,  'Metropolitan Police'),
(3,  'Cumbria'),
(4,  'Lancashire'),
(5,  'Merseyside'),
(6,  'Greater Manchester'),
(7,  'Cheshire'),
(10, 'Northumbria'),
(11, 'Durham'),
(12, 'North Yorkshire'),
(13, 'West Yorkshire'),
(14, 'South Yorkshire'),
(16, 'Humberside'),
(17, 'Cleveland'),
(20, 'West Midlands'),
(21, 'Staffordshire'),
(22, 'West Mercia'),
(23, 'Warwickshire'),
(30, 'Derbyshire'),
(31, 'Nottinghamshire'),
(32, 'Lincolnshire'),
(33, 'Leicestershire'),
(34, 'Northamptonshire'),
(35, 'Cambridgeshire'),
(36, 'Norfolk'),
(37, 'Suffolk'),
(40, 'Bedfordshire'),
(41, 'Hertfordshire'),
(42, 'Essex'),
(43, 'Thames Valley'),
(44, 'Hampshire'),
(45, 'Surrey'),
(46, 'Kent'),
(47, 'Sussex'),
(48, 'City of London'),
(50, 'Devon and Cornwall'),
(52, 'Avon and Somerset'),
(53, 'Gloucestershire'),
(54, 'Wiltshire'),
(55, 'Dorset'),
(60, 'North Wales'),
(61, 'Gwent'),
(62, 'South Wales'),
(63, 'Dyfed-Powys'),
(91, 'Northern'),
(92, 'Grampian'),
(93, 'Tayside'),
(94, 'Fife'),
(95, 'Lothian and Borders'),
(96, 'Central'),
(97, 'Strathclyde'),
(98, 'Dumfries and Galloway');


-- table police_force
CREATE TABLE Severity_Lookup (
  id TINYINT PRIMARY KEY NOT NULL,  
  val varchar(25) NOT NULL,  
);


INSERT INTO Severity_Lookup VALUES
(1,	'Fatal'),
(2,	'Serious'),
(3,	'Slight');


CREATE TABLE District_Lookup (
  id SMALLINT PRIMARY KEY NOT NULL,  
  val varchar(50) NOT NULL,  
);


INSERT INTO District_Lookup VALUES 
(1,	'Westminster'),
(2,	'Camden'),
(3,	'Islington'),
(4,	'Hackney'),
(5,	'Tower Hamlets'),
(6,	'Greenwich'),
(7,	'Lewisham'),
(8,	'Southwark'),
(9,	'Lambeth'),
(10, 'Wandsworth'),
(11, 'Hammersmith and Fulham'),
(12, 'Kensington and Chelsea'),
(13, 'Waltham Forest'),
(14, 'Redbridge'),
(15, 'Havering'),
(16, 'Barking and Dagenham'),
(17, 'Newham'),
(18, 'Bexley'),
(19, 'Bromley'),
(20, 'Croydon'),
(21, 'Sutton'),
(22, 'Merton'),
(23, 'Kingston upon Thames'),
(24, 'Richmond upon Thames'),
(25, 'Hounslow'),
(26, 'Hillingdon'),
(27, 'Ealing'),
(28, 'Brent'),
(29, 'Harrow'),
(30, 'Barnet'),
(31, 'Haringey'),
(32, 'Enfield'),
(33, 'Hertsmere'),
(38, 'Epsom and Ewell'),
(40, 'Spelthorne'),
(57, 'London Airport (Heathrow)'),
(60, 'Allerdale'),
(61, 'Barrow-in-Furness'),
(62, 'Carlisle'),
(63, 'Copeland'),
(64, 'Eden'),
(65, 'South Lakeland'),
(70, 'Blackburn with Darwen'),
(71, 'Blackpool'),
(72, 'Burnley'),
(73, 'Chorley'),
(74, 'Fylde'),
(75, 'Hyndburn'),
(76, 'Lancaster'),
(77, 'Pendle'),
(79, 'Preston'),
(80, 'Ribble Valley'),
(82, 'Rossendale'),
(83, 'South Ribble'),
(84, 'West Lancashire'),
(85, 'Wyre'),
(90, 'Knowsley'),
(91, 'Liverpool'),
(92, 'St. Helens'),
(93, 'Sefton'),
(95, 'Wirral'),
(100,	'Bolton'),
(101,	'Bury'),
(102,	'Manchester'),
(104,	'Oldham'),
(106,	'Rochdale'),
(107,	'Salford'),
(109,	'Stockport'),
(110,	'Tameside'),
(112,	'Trafford'),
(114,	'Wigan'),
(120,	'Chester'),
(121,	'Congleton'),
(122,	'Crewe and Nantwich'),
(123,	'Ellesmere Port and Neston'),
(124,	'Halton'),
(126,	'Macclesfield'),
(127,	'Vale Royal'),
(128,	'Warrington'),
(129,	'Cheshire East'),
(130,	'Cheshire West and Chester'),
(139,	'Northumberland'),
(140,	'Alnwick'),
(141,	'Berwick-upon-Tweed'),
(142,	'Blyth Valley'),
(143,	'Castle Morpeth'),
(144,	'Tynedale'),
(145,	'Wansbeck'),
(146,	'Gateshead'),
(147,	'Newcastle upon Tyne'),
(148,	'North Tyneside'),
(149,	'South Tyneside'),
(150,	'Sunderland'),
(160,	'Chester-le-Street'),
(161,	'Darlington'),
(162,	'Derwentside'),
(163,	'Durham'),
(164,	'Easington'),
(165,	'Sedgefield'),
(166,	'Teesdale'),
(168,	'Wear Valley'),
(169,	'County Durham'),
(180,	'Craven'),
(181,	'Hambleton'),
(182,	'Harrogate'),
(184,	'Richmondshire'),
(185,	'Ryedale'),
(186,	'Scarborough'),
(187,	'Selby'),
(189,	'York'),
(200,	'Bradford'),
(202,	'Calderdale'),
(203,	'Kirklees'),
(204,	'Leeds'),
(206,	'Wakefield'),
(210,	'Barnsley'),
(211,	'Doncaster'),
(213,	'Rotherham'),
(215,	'Sheffield'),
(228,	'Kingston upon Hull, City of'),
(231,	'East Riding of Yorkshire'),
(232,	'North Lincolnshire'),
(233,	'North East Lincolnshire'),
(240,	'Hartlepool'),
(241,	'Redcar and Cleveland'),
(243,	'Middlesbrough'),
(245,	'Stockton-on-Tees'),
(250,	'Cannock Chase'),
(251,	'East Staffordshire'),
(252,	'Lichfield'),
(253,	'Newcastle-under-Lyme'),
(254,	'South Staffordshire'),
(255,	'Stafford'),
(256,	'Staffordshire Moorlands'),
(257,	'Stoke-on-Trent'),
(258,	'Tamworth'),
(270,	'Bromsgrove'),
(273,	'Malvern Hills'),
(274,	'Redditch'),
(276,	'Worcester'),
(277,	'Wychavon'),
(278,	'Wyre Forest'),
(279,	'Bridgnorth'),
(280,	'North Shropshire'),
(281,	'Oswestry'),
(282,	'Shrewsbury and Atcham'),
(283,	'South Shropshire'),
(284,	'Telford and Wrekin'),
(285,	'Herefordshire, County of '),
(286,	'Shropshire'),
(290,	'North Warwickshire'),
(291,	'Nuneaton and Bedworth'),
(292,	'Rugby '),
(293,	'Stratford-upon-Avon'),
(294,	'Warwick'),
(300,	'Birmingham'),
(302,	'Coventry'),
(303,	'Dudley'),
(305,	'Sandwell'),
(306,	'Solihull'),
(307,	'Walsall'),
(309,	'Wolverhampton'),
(320,	'Amber Valley'),
(321,	'Bolsover'),
(322,	'Chesterfield'),
(323,	'Derby'),
(324,	'Erewash'),
(325,	'High Peak'),
(327,	'North East Derbyshire'),
(328,	'South Derbyshire'),
(329,	'Derbyshire Dales'),
(340,	'Ashfield'),
(341,	'Bassetlaw'),
(342,	'Broxtowe'),
(343,	'Gedling'),
(344,	'Mansfield'),
(345,	'Newark and Sherwood'),
(346,	'Nottingham'),
(347,	'Rushcliffe'),
(350,	'Boston'),
(351,	'East Lindsey'),
(352,	'Lincoln'),
(353,	'North Kesteven'),
(354,	'South Holland'),
(355,	'South Kesteven'),
(356,	'West Lindsey'),
(360,	'Blaby'),
(361,	'Hinckley and Bosworth'),
(362,	'Charnwood'),
(363,	'Harborough'),
(364,	'Leicester'),
(365,	'Melton'),
(366,	'North West Leicestershire'),
(367,	'Oadby and Wigston'),
(368,	'Rutland'),
(380,	'Corby'),
(381,	'Daventry'),
(382,	'East Northamptonshire'),
(383,	'Kettering'),
(384,	'Northampton'),
(385,	'South Northamptonshire'),
(386,	'Wellingborough'),
(390,	'Cambridge'),
(391,	'East Cambridgeshire'),
(392,	'Fenland'),
(393,	'Huntingdonshire'),
(394,	'Peterborough'),
(395,	'South Cambridgeshire'),
(400,	'Breckland'),
(401,	'Broadland'),
(402,	'Great Yarmouth'),
(404,	'Norwich'),
(405,	'North Norfolk'),
(406,	'South Norfolk'),
(407,	'King s Lynn and West Norfolk'),
(410,	'Babergh'),
(411,	'Forest Heath'),
(412,	'Ipswich'),
(413,	'Mid Suffolk'),
(414,	'St. Edmundsbury'),
(415,	'Suffolk Coastal'),
(416,	'Waveney'),
(420,	'Bedford'),
(421,	'Luton'),
(422,	'Mid Bedfordshire'),
(423,	'South Bedfordshire'),
(424,	'Central Bedfordshire'),
(430,	'Broxbourne'),
(431,	'Dacorum'),
(432,	'East Hertfordshire'),
(433,	'North Hertfordshire'),
(434,	'St. Albans'),
(435,	'Stevenage'),
(436,	'Three Rivers'),
(437,	'Watford'),
(438,	'Welwyn Hatfield'),
(450,	'Basildon'),
(451,	'Braintree'),
(452,	'Brentwood'),
(453,	'Castle Point'),
(454,	'Chelmsford'),
(455,	'Colchester'),
(456,	'Epping Forest'),
(457,	'Harlow'),
(458,	'Maldon'),
(459,	'Rochford'),
(460,	'Southend-on-Sea'),
(461,	'Tendring'),
(462,	'Thurrock'),
(463,	'Uttlesford'),
(470,	'Bracknell Forest'),
(471,	'West Berkshire'),
(472,	'Reading'),
(473,	'Slough'),
(474,	'Windsor and Maidenhead'),
(475,	'Wokingham'),
(476,	'Aylesbury Vale'),
(477,	'South Bucks'),
(478,	'Chiltern'),
(479,	'Milton Keynes'),
(480,	'Wycombe'),
(481,	'Cherwell'),
(482,	'Oxford'),
(483,	'Vale of White Horse'),
(484,	'South Oxfordshire'),
(485,	'West Oxfordshire'),
(490,	'Basingstoke and Deane'),
(491,	'Eastleigh'),
(492,	'Fareham'),
(493,	'Gosport'),
(494,	'Hart'),
(495,	'Havant'),
(496,	'New Forest'),
(497,	'East Hampshire'),
(498,	'Portsmouth'),
(499,	'Rushmoor'),
(500,	'Southampton '),
(501,	'Test Valley'),
(502,	'Winchester'),
(505,	'Isle of Wight'),
(510,	'Elmbridge'),
(511,	'Guildford'),
(512,	'Mole Valley'),
(513,	'Reigate and Banstead'),
(514,	'Runnymede'),
(515,	'Surrey Heath'),
(516,	'Tandridge'),
(517,	'Waverley'),
(518,	'Woking'),
(530,	'Ashford'),
(531,	'Canterbury'),
(532,	'Dartford'),
(533,	'Dover'),
(535,	'Gravesham'),
(536,	'Maidstone'),
(538,	'Sevenoaks'),
(539,	'Shepway'),
(540,	'Swale'),
(541,	'Thanet'),
(542,	'Tonbridge and Malling'),
(543,	'Tunbridge Wells'),
(544,	'Medway'),
(551,	'Eastbourne'),
(552,	'Hastings'),
(554,	'Lewes'),
(555,	'Rother'),
(556,	'Wealden'),
(557,	'Adur'),
(558,	'Arun'),
(559,	'Chichester'),
(560,	'Crawley'),
(562,	'Horsham'),
(563,	'Mid Sussex'),
(564,	'Worthing'),
(565,	'Brighton and Hove'),
(570,	'City of London'),
(580,	'East Devon'),
(581,	'Exeter'),
(582,	'North Devon'),
(583,	'Plymouth'),
(584,	'South Hams'),
(585,	'Teignbridge'),
(586,	'Mid Devon'),
(587,	'Torbay'),
(588,	'Torridge'),
(589,	'West Devon'),
(590,	'Caradon'),
(591,	'Carrick'),
(592,	'Kerrier'),
(593,	'North Cornwall'),
(594,	'Penwith'),
(595,	'Restormel'),
(596,	'Cornwall'),
(601,	'Bristol, City of'),
(605,	'North Somerset'),
(606,	'Mendip'),
(607,	'Sedgemoor'),
(608,	'Taunton Deane'),
(609,	'West Somerset'),
(610,	'South Somerset'),
(611,	'Bath and North East Somerset'),
(612,	'South Gloucestershire'),
(620,	'Cheltenham'),
(621,	'Cotswold'),
(622,	'Forest of Dean'),
(623,	'Gloucester'),
(624,	'Stroud'),
(625,	'Tewkesbury'),
(630,	'Kennet'),
(631,	'North Wiltshire'),
(632,	'Salisbury'),
(633,	'Swindon'),
(634,	'West Wiltshire'),
(635,	'Wiltshire'),
(640,	'Bournemouth'),
(641,	'Christchurch'),
(642,	'North Dorset'),
(643,	'Poole'),
(644,	'Purbeck'),
(645,	'West Dorset'),
(646,	'Weymouth and Portland'),
(647,	'East Dorset'),
(720,	'Isle of Anglesey'),
(721,	'Conwy'),
(722,	'Gwynedd'),
(723,	'Denbighshire'),
(724,	'Flintshire'),
(725,	'Wrexham'),
(730,	'Blaenau Gwent'),
(731,	'Caerphilly'),
(732,	'Monmouthshire'),
(733,	'Newport'),
(734,	'Torfaen'),
(740,	'Bridgend'),
(741,	'Cardiff'),
(742,	'Merthyr Tydfil'),
(743,	'Neath Port Talbot'),
(744,	'Rhondda, Cynon, Taff'),
(745,	'Swansea'),
(746,	'The Vale of Glamorgan'),
(750,	'Ceredigion'),
(751,	'Carmarthenshire'),
(752,	'Pembrokeshire'),
(753,	'Powys'),
(910,	'Aberdeen City'),
(911,	'Aberdeenshire'),
(912,	'Angus'),
(913,	'Argyll and Bute'),
(914,	'Scottish Borders'),
(915,	'Clackmannanshire'),
(916,	'West Dunbartonshire'),
(917,	'Dumfries and Galloway'),
(918,	'Dundee City'),
(919,	'East Ayrshire'),
(920,	'East Dunbartonshire'),
(921,	'East Lothian'),
(922,	'East Renfrewshire'),
(923,	'Edinburgh, City of'),
(924,	'Falkirk'),
(925,	'Fife'),
(926,	'Glasgow City'),
(927,	'Highland'),
(928,	'Inverclyde'),
(929,	'Midlothian'),
(930,	'Moray'),
(931,	'North Ayrshire'),
(932,	'North Lanarkshire'),
(933,	'Orkney Islands'),
(934,	'Perth and Kinross'),
(935,	'Renfrewshire'),
(936,	'Shetland Islands'),
(937,	'South Ayrshire'),
(938,	'South Lanarkshire'),
(939,	'Stirling'),
(940,	'West Lothian'),
(941,	'Western Isles');


-- table accident
CREATE TABLE Accidents (

	id char(14) NOT NULL,
	Date date NOT NULL,
	Time time NOT NULL,
	District SMALLINT NOT NULL,

	Police_force TINYINT NOT NULL,
	Police_attend TINYINT NOT NULL,
	Severity TINYINT NOT NULL,
	Road_type TINYINT NOT NULL,
	Weather_cond TINYINT NOT NULL,
	Road_surface TINYINT NOT NULL,

	PRIMARY KEY(id),
	CONSTRAINT fk_acc_pol FOREIGN KEY (Police_force) REFERENCES Police_Force_Lookup(id),
	CONSTRAINT fk_acc_dis FOREIGN KEY (District) REFERENCES District_Lookup(id),
	CONSTRAINT fk_acc_sev FOREIGN KEY (Severity) REFERENCES Severity_Lookup(id),
	CONSTRAINT fk_road_cond FOREIGN KEY (Road_type) REFERENCES Road_Type_Lookup(id),
	CONSTRAINT fk_weather FOREIGN KEY (Weather_cond) REFERENCES Weather_Lookup(id),
	CONSTRAINT fk_road_surf FOREIGN KEY (Road_surface) REFERENCES Road_Surface_Lookup(id),
);


-- table 2.5/2.5a
CREATE TABLE Vehicle_Type_Lookup (
  id TINYINT PRIMARY KEY NOT NULL,  
  val varchar(100) NOT NULL,  
);


INSERT INTO Vehicle_Type_Lookup VALUES
(9,  'Car'),
(8,  'Taxi / Private hire car'),
(19, 'Van - Goods vehicle 3.5 tonnes mgw and under'),
(20, 'Goods vehicle over 3.5 tonnes mgw and under 7.5 tonnes mgw'),
(21, 'Goods vehicle 7.5 tonnes mgw & over'),
(98, 'Goods vehicle - unknown weight'),
(2,  'M/cycle 50cc and under'),
(3,  'M/cycle over 50cc and up to 125cc'),
(4,  'M/cycle over 125cc and up to 500cc'),
(5,  'Motorcycle over 500cc'),
(97, 'Motorcycle - cc unknown'),
(23, 'Electric Motorcycle'),
(1,  'Pedal cycle'),
(11, 'Bus or coach (17 or more passenger seats)'),
(10, 'Minibus (8-16 passenger seats)'),
(17, 'Agricultural vehicle (include diggers etc)'),
(16, 'Ridden horse'),
(22, 'Mobility scooter'),
(18, 'Tram / Light rail');


-- table 2.21
CREATE TABLE Sex_Lookup (
  id TINYINT PRIMARY KEY NOT NULL,  
  val varchar(15) NOT NULL,  
);

INSERT INTO Sex_Lookup VALUES
(1, 'Male'),
(2, 'Female');


-- table vehicles
CREATE TABLE Vehicles (

	acc_id char(14) NOT NULL,
	veh_id TINYINT NOT NULL,

	veh_type TINYINT NOT NULL,
	dr_age TINYINT NOT NULL,
	dr_sex TINYINT NOT NULL,
	veh_age TINYINT NOT NULL,
	engine_cc INT NOT NULL,

	PRIMARY KEY(acc_id, veh_id),
	CONSTRAINT fk_veh_acc FOREIGN KEY (acc_id) REFERENCES Accidents(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_veh_type FOREIGN KEY (veh_type) REFERENCES Vehicle_Type_Lookup(id),
	CONSTRAINT fk_dr_sex FOREIGN KEY (dr_sex) REFERENCES Sex_Lookup(id),
);


-- table casualties
CREATE TABLE Casualties (

	acc_id char(14) NOT NULL,
	veh_id TINYINT NOT NULL,
	cas_id TINYINT NOT NULL,

	cas_sex TINYINT NOT NULL,
	cas_sev TINYINT NOT NULL,

	PRIMARY KEY(acc_id, veh_id, cas_id),
	CONSTRAINT fk_cas_veh FOREIGN KEY (acc_id, veh_id) REFERENCES Vehicles(acc_id, veh_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_cas_sev FOREIGN KEY (cas_sev) REFERENCES Severity_Lookup(id),
	CONSTRAINT fk_cas_sex FOREIGN KEY (cas_sex) REFERENCES Sex_Lookup(id)
);
